"use client";

import { useEffect, useMemo, useState } from "react";
import { translateEnum } from "@/lib/i18n";
import { useLocale } from "@/lib/locale-context";
import { listSavedReports, type SavedReport } from "@/lib/saved-reports";

function topRashis(report: SavedReport) { return [...(report.handoff.ashtakavarga?.sarvashtakavarga ?? [])].sort((a, b) => b.points - a.points).slice(0, 3); }
function currentDasha(report: SavedReport) { const today = new Date().toISOString().slice(0, 10); return report.handoff.dasha?.periods.find((period) => period.start_date <= today && today < period.end_date) ?? null; }

export function ReportComparison() {
  const { dict } = useLocale(); const [reports, setReports] = useState<SavedReport[]>([]); const [leftId, setLeftId] = useState(""); const [rightId, setRightId] = useState(""); useEffect(() => setReports(listSavedReports()), []);
  const [left, right] = useMemo(() => [reports.find((report) => report.id === leftId), reports.find((report) => report.id === rightId)], [reports, leftId, rightId]);
  return <section className="heritage-card w-full rounded-2xl border p-4 shadow-sm sm:p-5"><p className="text-sm opacity-75">{dict.ui.reportComparisonDescription}</p>{reports.length < 2 ? <p className="mt-4">{dict.ui.reportComparisonNeedTwo}</p> : <><div className="mt-4 grid gap-3 md:grid-cols-2"><select value={leftId} onChange={(event) => setLeftId(event.target.value)} className="min-h-11 rounded-lg border bg-transparent px-3"><option value="">{dict.ui.chooseFirstReport}</option>{reports.map((report) => <option key={report.id} value={report.id}>{report.label}</option>)}</select><select value={rightId} onChange={(event) => setRightId(event.target.value)} className="min-h-11 rounded-lg border bg-transparent px-3"><option value="">{dict.ui.chooseSecondReport}</option>{reports.filter((report) => report.id !== leftId).map((report) => <option key={report.id} value={report.id}>{report.label}</option>)}</select></div>{left && right && <div className="mt-5 grid gap-4 lg:grid-cols-2">{[left, right].map((report) => { const ashta = report.handoff.ashtakavarga; const chart = report.handoff.chart; const dasha = currentDasha(report); const divisional = report.handoff.divisional; const top = topRashis(report); return <article key={report.id} className="rounded-xl border border-black/10 p-4 dark:border-white/10"><h2 className="font-semibold">{report.label}</h2><dl className="mt-3 grid gap-3 text-sm">{chart && <div><dt className="text-xs font-semibold uppercase opacity-70">{dict.ui.comparisonAscendant}</dt><dd>{translateEnum(dict, "rashis", chart.ascendant_rashi_key)}</dd></div>}{dasha && <div><dt className="text-xs font-semibold uppercase opacity-70">{dict.ui.insightsCurrentDasha}</dt><dd>{translateEnum(dict, "horaPlanets", dasha.key)}</dd></div>}{divisional && <div><dt className="text-xs font-semibold uppercase opacity-70">{dict.ui.comparisonDivisional}</dt><dd>{dict.ui.comparisonAvailable}</dd></div>}{ashta ? <div><dt className="text-xs font-semibold uppercase opacity-70">{dict.ashtakavarga.total}</dt><dd className="font-semibold text-accent">{ashta.total_points}</dd><dt className="mt-2 text-xs font-semibold uppercase opacity-70">{dict.ui.topRashis}</dt><dd>{top.map((house) => `${translateEnum(dict, "rashis", house.rashi_key)} (${house.points})`).join(" · ")}</dd></div> : <p className="opacity-75">{dict.ui.reportComparisonNoAshtakavarga}</p>}</dl></article>; })}</div>}</>}</section>;
}
