"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useLocale } from "@/lib/locale-context";
import { deleteSavedReport, listSavedReports, renameSavedReport, restoreSavedReport, type SavedReport } from "@/lib/saved-reports";

export function SavedReportsWorkspace() {
  const { dict, locale } = useLocale(); const router = useRouter(); const [reports, setReports] = useState<SavedReport[]>([]); const [notice, setNotice] = useState("");
  const refresh = () => setReports(listSavedReports()); useEffect(refresh, []);
  return <section className="heritage-card rounded-2xl border p-4 shadow-sm sm:p-5"><p className="text-sm opacity-75">{dict.ui.deviceOnly}</p>{notice && <p role="status" className="mt-3 rounded-lg bg-accent/10 px-3 py-2 text-sm">{notice}</p>}{reports.length === 0 ? <p className="mt-4">{dict.ui.noSavedReports}</p> : <div className="mt-4 grid gap-3">{reports.map((report) => <article key={report.id} className="rounded-xl border border-black/10 p-4 dark:border-white/10"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{report.label}</h2><p className="text-xs opacity-70">{new Date(report.createdAt).toLocaleString()}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => { const restored = restoreSavedReport(report.id); if (restored) router.push(`/${locale}${restored.reportPath}`); }} className="rounded-lg bg-accent px-3 py-1.5 text-sm font-semibold text-white">{dict.ui.open}</button><button onClick={() => { const label = window.prompt(dict.ui.profileLabelPrompt, report.label); if (label) { renameSavedReport(report.id, label); refresh(); } }} className="rounded-lg border px-3 py-1.5 text-sm">{dict.ui.rename}</button><button onClick={() => { const url = URL.createObjectURL(new Blob([JSON.stringify(report, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `${report.label.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "report"}.json`; link.click(); URL.revokeObjectURL(url); setNotice(dict.ui.reportExported); }} className="rounded-lg border px-3 py-1.5 text-sm">{dict.ui.export}</button><button onClick={() => { if (window.confirm(report.label)) { deleteSavedReport(report.id); refresh(); setNotice(dict.ui.reportDeleted); } }} className="rounded-lg border px-3 py-1.5 text-sm">{dict.ui.remove}</button></div></div></article>)}</div>}</section>;
}
