"use client";

import { useEffect, useRef, useState } from "react";
import { listPrivateBirthProfiles, removePrivateBirthProfile, savePrivateBirthProfile, type PrivateBirthProfile } from "@/lib/private-birth-profiles";
import { useLocale } from "@/lib/locale-context";

export function PrivateBirthVault() {
  const { dict } = useLocale(); const [profiles, setProfiles] = useState<PrivateBirthProfile[]>([]); const [notice, setNotice] = useState(""); const fileRef = useRef<HTMLInputElement>(null); const refresh = () => setProfiles(listPrivateBirthProfiles()); useEffect(refresh, []);
  const download = (profile: PrivateBirthProfile) => { const url = URL.createObjectURL(new Blob([JSON.stringify(profile, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `${profile.label.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "private-profile"}.json`; link.click(); URL.revokeObjectURL(url); };
  const importProfile = async (file: File) => { if (file.size > 50_000) { setNotice(dict.ui.privateProfileImportInvalid); return; } try { const parsed = JSON.parse(await file.text()) as Partial<PrivateBirthProfile>; if (!parsed.label || !parsed.input?.birthDate || !parsed.input.birthTime || !parsed.input.location?.iana_tz) throw new Error("invalid"); savePrivateBirthProfile(parsed.label, parsed.input); refresh(); setNotice(dict.ui.privateProfileImported); } catch { setNotice(dict.ui.privateProfileImportInvalid); } };
  return <section className="heritage-card rounded-2xl border p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{dict.ui.privateBirthProfiles}</h2><p className="mt-1 text-sm opacity-75">{dict.ui.privateBirthProfilesNote}</p></div><input ref={fileRef} type="file" accept="application/json" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importProfile(file); event.currentTarget.value = ""; }} /><button type="button" onClick={() => fileRef.current?.click()} className="rounded-lg border px-3 py-1.5 text-sm">{dict.ui.importProfile}</button></div>{notice && <p role="status" className="mt-3 text-sm text-accent">{notice}</p>}{profiles.length === 0 ? <p className="mt-4">{dict.ui.emptyPrivateBirthProfiles}</p> : <div className="mt-4 grid gap-3">{profiles.map((profile) => <article key={profile.id} className="flex flex-col gap-3 rounded-xl border border-black/10 p-4 sm:flex-row sm:items-center sm:justify-between dark:border-white/10"><div><h3 className="font-semibold">{profile.label}</h3><p className="text-xs opacity-70">{profile.input.location.name}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => { const label = window.prompt(dict.ui.profileLabelPrompt, profile.label); if (label) { savePrivateBirthProfile(label, profile.input); refresh(); } }} className="rounded-lg border px-3 py-1.5 text-sm">{dict.ui.rename}</button><button type="button" onClick={() => download(profile)} className="rounded-lg border px-3 py-1.5 text-sm">{dict.ui.export}</button><button type="button" onClick={() => { if (window.confirm(profile.label)) { removePrivateBirthProfile(profile.id); refresh(); } }} className="rounded-lg border px-3 py-1.5 text-sm">{dict.ui.remove}</button></div></article>)}</div>}</section>;
}
