/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/compatibility/birds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Birds */
        post: operations["birds_api_v1_compatibility_birds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform Metadata */
        get: operations["platform_metadata_api_v1_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pancha-pakshi/birth-bird": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Birth Bird */
        post: operations["birth_bird_api_v1_pancha_pakshi_birth_bird_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pancha-pakshi/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Current */
        post: operations["current_api_v1_pancha_pakshi_current_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pancha-pakshi/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metadata */
        get: operations["metadata_api_v1_pancha_pakshi_metadata_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pancha-pakshi/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule */
        post: operations["schedule_api_v1_pancha_pakshi_schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pancha-pakshi/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Summary */
        post: operations["summary_api_v1_pancha_pakshi_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pancha-pakshi/windows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Windows */
        post: operations["windows_api_v1_pancha_pakshi_windows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/panchanga/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Daily */
        post: operations["daily_api_v1_panchanga_daily_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityId
         * @enum {string}
         */
        ActivityId: "ruling" | "eating" | "walking" | "sleeping" | "dying";
        /**
         * BirdId
         * @enum {string}
         */
        BirdId: "vulture" | "owl" | "crow" | "cock" | "peacock";
        /** BirdSelectionInput */
        BirdSelectionInput: {
            /** As Of Date */
            as_of_date?: string | null;
            /** As Of Time */
            as_of_time?: string | null;
            bird: components["schemas"]["BirdId"];
            /** Iana Tz */
            iana_tz: string;
            /** Latitude */
            latitude: number;
            /** Location Name */
            location_name: string;
            /** Longitude */
            longitude: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "bird";
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Target Time
             * Format: time
             */
            target_time: string;
        };
        /** BirdSelectionSummaryInput */
        BirdSelectionSummaryInput: {
            /** As Of Date */
            as_of_date?: string | null;
            /** As Of Time */
            as_of_time?: string | null;
            bird: components["schemas"]["BirdId"];
            /**
             * Days
             * @default 31
             */
            days: number;
            /** Iana Tz */
            iana_tz: string;
            /** Latitude */
            latitude: number;
            /** Location Name */
            location_name: string;
            /** Longitude */
            longitude: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "bird";
            /**
             * Min Effect
             * @default good
             * @enum {string}
             */
            min_effect: "good" | "very_good";
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Target Time
             * Format: time
             */
            target_time: string;
        };
        /** BirdSelectionWindowsInput */
        BirdSelectionWindowsInput: {
            /** Activities */
            activities?: components["schemas"]["ActivityId"][] | null;
            /** As Of Date */
            as_of_date?: string | null;
            /** As Of Time */
            as_of_time?: string | null;
            bird: components["schemas"]["BirdId"];
            /**
             * Days
             * @default 7
             */
            days: number;
            /** Iana Tz */
            iana_tz: string;
            /** Kinds */
            kinds?: components["schemas"]["PeriodKind"][] | null;
            /** Latitude */
            latitude: number;
            /** Location Name */
            location_name: string;
            /** Longitude */
            longitude: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "bird";
            /** Min Duration Seconds */
            min_duration_seconds?: number | null;
            /**
             * Min Effect
             * @default good
             * @enum {string}
             */
            min_effect: "good" | "very_good";
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Target Time
             * Format: time
             */
            target_time: string;
        };
        /** BirthBirdResponse */
        BirthBirdResponse: {
            bharana_pakshi: components["schemas"]["BirdId"];
            birth_bird: components["schemas"]["BirdId"];
            padu_pakshi: components["schemas"]["BirdId"];
        };
        /** BirthDateTimeInput */
        BirthDateTimeInput: {
            /** As Of Date */
            as_of_date?: string | null;
            /** As Of Time */
            as_of_time?: string | null;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /**
             * Birth Time
             * Format: time
             */
            birth_time: string;
            /** Iana Tz */
            iana_tz: string;
            /** Latitude */
            latitude: number;
            /** Location Name */
            location_name: string;
            /** Longitude */
            longitude: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "birth_datetime";
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Target Time
             * Format: time
             */
            target_time: string;
        };
        /** BirthDateTimeSummaryInput */
        BirthDateTimeSummaryInput: {
            /** As Of Date */
            as_of_date?: string | null;
            /** As Of Time */
            as_of_time?: string | null;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /**
             * Birth Time
             * Format: time
             */
            birth_time: string;
            /**
             * Days
             * @default 31
             */
            days: number;
            /** Iana Tz */
            iana_tz: string;
            /** Latitude */
            latitude: number;
            /** Location Name */
            location_name: string;
            /** Longitude */
            longitude: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "birth_datetime";
            /**
             * Min Effect
             * @default good
             * @enum {string}
             */
            min_effect: "good" | "very_good";
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Target Time
             * Format: time
             */
            target_time: string;
        };
        /** BirthDateTimeWindowsInput */
        BirthDateTimeWindowsInput: {
            /** Activities */
            activities?: components["schemas"]["ActivityId"][] | null;
            /** As Of Date */
            as_of_date?: string | null;
            /** As Of Time */
            as_of_time?: string | null;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /**
             * Birth Time
             * Format: time
             */
            birth_time: string;
            /**
             * Days
             * @default 7
             */
            days: number;
            /** Iana Tz */
            iana_tz: string;
            /** Kinds */
            kinds?: components["schemas"]["PeriodKind"][] | null;
            /** Latitude */
            latitude: number;
            /** Location Name */
            location_name: string;
            /** Longitude */
            longitude: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "birth_datetime";
            /** Min Duration Seconds */
            min_duration_seconds?: number | null;
            /**
             * Min Effect
             * @default good
             * @enum {string}
             */
            min_effect: "good" | "very_good";
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Target Time
             * Format: time
             */
            target_time: string;
        };
        /** CompatibilityRequest */
        CompatibilityRequest: {
            bird_a: components["schemas"]["BirdId"];
            bird_b: components["schemas"]["BirdId"];
        };
        /** CompatibilityResponse */
        CompatibilityResponse: {
            bird_a: components["schemas"]["BirdId"];
            bird_b: components["schemas"]["BirdId"];
            /** Context Dependent */
            context_dependent: boolean;
            relation: components["schemas"]["RelationId"];
            /** Sample Size */
            sample_size: number;
            /** Variants */
            variants: components["schemas"]["RelationVariant"][];
        };
        /** DailyPanchanga */
        DailyPanchanga: {
            /**
             * Date
             * Format: date
             */
            date: string;
            engine: components["schemas"]["EngineMetadata"];
            /** Is Poya Day */
            is_poya_day: boolean;
            kalams: components["schemas"]["Kalams"];
            /** Karana */
            karana: components["schemas"]["KaranaSpan"][];
            location: components["schemas"]["Location"];
            lunar_month: components["schemas"]["LunarMonth"];
            /** Moonrise */
            moonrise: string | null;
            /** Moonset */
            moonset: string | null;
            /** Nakshatra */
            nakshatra: components["schemas"]["NakshatraSpan"][];
            next_poya: components["schemas"]["NextPoya"];
            paksha: components["schemas"]["PakshaId"];
            poya: components["schemas"]["PoyaInfo"] | null;
            sinhala_month: components["schemas"]["SinhalaMonth"];
            /**
             * Sunrise
             * Format: date-time
             */
            sunrise: string;
            /**
             * Sunset
             * Format: date-time
             */
            sunset: string;
            /** Tithi */
            tithi: components["schemas"]["TithiSpan"][];
            weekday: components["schemas"]["WeekdayId"];
            /** Yoga */
            yoga: components["schemas"]["YogaSpan"][];
        };
        /** DailyPanchangaRequest */
        DailyPanchangaRequest: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Iana Tz */
            iana_tz: string;
            /** Latitude */
            latitude: number;
            /** Location Name */
            location_name: string;
            /** Longitude */
            longitude: number;
        };
        /**
         * EffectId
         * @enum {string}
         */
        EffectId: "very_bad" | "bad" | "average" | "good" | "very_good";
        /** EngineMetadata */
        EngineMetadata: {
            /** Commit */
            commit: string;
            /** Csv Checksum */
            csv_checksum: string;
            /** Deployed Commit */
            deployed_commit: string;
            /** Ephemeris Manifest Checksum */
            ephemeris_manifest_checksum: string;
            /**
             * Name
             * @default PyJHora
             */
            name: string;
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KalamRange */
        KalamRange: {
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
        };
        /** Kalams */
        Kalams: {
            gulika: components["schemas"]["KalamRange"];
            rahu: components["schemas"]["KalamRange"];
            yamaganda: components["schemas"]["KalamRange"];
        };
        /** KaranaSpan */
        KaranaSpan: {
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Index 60 */
            index_60: number;
            /** Key */
            key: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
        };
        /** Location */
        Location: {
            /** Iana Tz */
            iana_tz: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name: string;
            /** Utc Offset Minutes */
            utc_offset_minutes: number;
        };
        /** LunarMonth */
        LunarMonth: {
            /** Index */
            index: number;
            /** Is Leap */
            is_leap: boolean;
            /** Key */
            key: string;
        };
        /** MajorPeriod */
        MajorPeriod: {
            bharana_pakshi: components["schemas"]["BirdId"];
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Index */
            index: number;
            kind: components["schemas"]["PeriodKind"];
            main_activity: components["schemas"]["ActivityId"];
            main_bird: components["schemas"]["BirdId"];
            padu_pakshi: components["schemas"]["BirdId"];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Sub Periods */
            sub_periods: components["schemas"]["SubPeriod"][];
        };
        /** NakshatraPakshaInput */
        NakshatraPakshaInput: {
            /** As Of Date */
            as_of_date?: string | null;
            /** As Of Time */
            as_of_time?: string | null;
            /** Iana Tz */
            iana_tz: string;
            /** Latitude */
            latitude: number;
            /** Location Name */
            location_name: string;
            /** Longitude */
            longitude: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "nakshatra_paksha";
            /** Nakshatra Index */
            nakshatra_index: number;
            paksha: components["schemas"]["PakshaId"];
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Target Time
             * Format: time
             */
            target_time: string;
        };
        /** NakshatraPakshaSummaryInput */
        NakshatraPakshaSummaryInput: {
            /** As Of Date */
            as_of_date?: string | null;
            /** As Of Time */
            as_of_time?: string | null;
            /**
             * Days
             * @default 31
             */
            days: number;
            /** Iana Tz */
            iana_tz: string;
            /** Latitude */
            latitude: number;
            /** Location Name */
            location_name: string;
            /** Longitude */
            longitude: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "nakshatra_paksha";
            /**
             * Min Effect
             * @default good
             * @enum {string}
             */
            min_effect: "good" | "very_good";
            /** Nakshatra Index */
            nakshatra_index: number;
            paksha: components["schemas"]["PakshaId"];
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Target Time
             * Format: time
             */
            target_time: string;
        };
        /** NakshatraPakshaWindowsInput */
        NakshatraPakshaWindowsInput: {
            /** Activities */
            activities?: components["schemas"]["ActivityId"][] | null;
            /** As Of Date */
            as_of_date?: string | null;
            /** As Of Time */
            as_of_time?: string | null;
            /**
             * Days
             * @default 7
             */
            days: number;
            /** Iana Tz */
            iana_tz: string;
            /** Kinds */
            kinds?: components["schemas"]["PeriodKind"][] | null;
            /** Latitude */
            latitude: number;
            /** Location Name */
            location_name: string;
            /** Longitude */
            longitude: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            method: "nakshatra_paksha";
            /** Min Duration Seconds */
            min_duration_seconds?: number | null;
            /**
             * Min Effect
             * @default good
             * @enum {string}
             */
            min_effect: "good" | "very_good";
            /** Nakshatra Index */
            nakshatra_index: number;
            paksha: components["schemas"]["PakshaId"];
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Target Time
             * Format: time
             */
            target_time: string;
        };
        /** NakshatraSpan */
        NakshatraSpan: {
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Index */
            index: number;
            /** Key */
            key: string;
            /** Pada */
            pada: number;
            /** Starts At */
            starts_at: string | null;
        };
        /** NextPoya */
        NextPoya: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Month Key */
            month_key: string;
        };
        /**
         * PakshaId
         * @enum {string}
         */
        PakshaId: "waxing" | "waning";
        /**
         * PeriodKind
         * @enum {string}
         */
        PeriodKind: "day" | "night";
        /** PoyaInfo */
        PoyaInfo: {
            /** Month Key */
            month_key: string;
        };
        /**
         * RelationId
         * @enum {string}
         */
        RelationId: "enemy" | "same" | "friend";
        /** RelationVariant */
        RelationVariant: {
            /** Count */
            count: number;
            relation: components["schemas"]["RelationId"];
        };
        /** ScheduleResponse */
        ScheduleResponse: {
            bharana_pakshi: components["schemas"]["BirdId"];
            birth_bird: components["schemas"]["BirdId"];
            current_period: components["schemas"]["SubPeriod"] | null;
            engine: components["schemas"]["EngineMetadata"];
            location: components["schemas"]["Location"];
            /** Major Periods */
            major_periods: components["schemas"]["MajorPeriod"][];
            next_period: components["schemas"]["SubPeriod"] | null;
            /**
             * Next Sunrise
             * Format: date-time
             */
            next_sunrise: string;
            padu_pakshi: components["schemas"]["BirdId"];
            paksha: components["schemas"]["PakshaId"];
            summary: components["schemas"]["ScheduleSummary"];
            /**
             * Sunrise
             * Format: date-time
             */
            sunrise: string;
            /**
             * Sunset
             * Format: date-time
             */
            sunset: string;
            weekday: components["schemas"]["WeekdayId"];
        };
        /** ScheduleSummary */
        ScheduleSummary: {
            /**
             * Major Period Count
             * @default 10
             */
            major_period_count: number;
            /**
             * Sub Period Count
             * @default 50
             */
            sub_period_count: number;
        };
        /** SinhalaMonth */
        SinhalaMonth: {
            /** Is Adhi */
            is_adhi: boolean;
            /** Key */
            key: string;
        };
        /** SubPeriod */
        SubPeriod: {
            /** Duration Seconds */
            duration_seconds: number;
            effect: components["schemas"]["EffectId"];
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Id */
            id: string;
            /** Is Current */
            is_current: boolean;
            kind: components["schemas"]["PeriodKind"];
            main_activity: components["schemas"]["ActivityId"];
            main_bird: components["schemas"]["BirdId"];
            /** Major Index */
            major_index: number;
            /** Power Factor */
            power_factor: number;
            /** Rating */
            rating: number;
            relation: components["schemas"]["RelationId"];
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            sub_activity: components["schemas"]["ActivityId"];
            sub_bird: components["schemas"]["BirdId"];
            /** Sub Index */
            sub_index: number;
        };
        /** TithiSpan */
        TithiSpan: {
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Index */
            index: number;
            /** Key */
            key: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WeekdayId
         * @enum {string}
         */
        WeekdayId: "sunday" | "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday";
        /** YogaSpan */
        YogaSpan: {
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Index */
            index: number;
            /** Key */
            key: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    birds_api_v1_compatibility_birds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompatibilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatibilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    platform_metadata_api_v1_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    birth_bird_api_v1_pancha_pakshi_birth_bird_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BirthDateTimeInput"] | components["schemas"]["NakshatraPakshaInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BirthBirdResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_api_v1_pancha_pakshi_current_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BirthDateTimeInput"] | components["schemas"]["NakshatraPakshaInput"] | components["schemas"]["BirdSelectionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metadata_api_v1_pancha_pakshi_metadata_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineMetadata"];
                };
            };
        };
    };
    schedule_api_v1_pancha_pakshi_schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BirthDateTimeInput"] | components["schemas"]["NakshatraPakshaInput"] | components["schemas"]["BirdSelectionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_pancha_pakshi_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BirthDateTimeSummaryInput"] | components["schemas"]["NakshatraPakshaSummaryInput"] | components["schemas"]["BirdSelectionSummaryInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    windows_api_v1_pancha_pakshi_windows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BirthDateTimeWindowsInput"] | components["schemas"]["NakshatraPakshaWindowsInput"] | components["schemas"]["BirdSelectionWindowsInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_api_v1_panchanga_daily_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyPanchangaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyPanchanga"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
